Update workflow

diff --git a/.github/workflows/parallel_test_allure_slack.yml b/.github/workflows/parallel_test_allure_slack.yml
--- a/.github/workflows/parallel_test_allure_slack.yml
+++ b/.github/workflows/parallel_test_allure_slack.yml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Run Parallel Test with Allure Report and Slack Notification
+name: Temp workflow
 
 on:
   workflow_dispatch:
@@ -16,95 +16,98 @@ jobs:
     runs-on: macos-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        pip install -r requirements.txt
-    - name: Install Node.js and npm
-      uses: actions/setup-node@v2
-      with:
-        node-version: '14'
-    - name: Install allure-commandline
-      run: npm install -g allure-commandline
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
-      id: test
-      run: pytest -n auto --dist loadfile  --alluredir=reports ./tests
-    - name: Generate Allure report
-      if: success() || failure()
-      run: allure generate reports  -o reports_allure
-    - name: Upload Allure report to Webpage
-      if: success() || failure()
-      run: |
-        git clone https://github.com/trang63/allure_report.git destination-repo
-        sudo systemsetup -settimezone "Asia/Ho_Chi_Minh"
-        current_date=$(date +%Y-%m-%d)
-        current_time=$(date +%H-%M-%S)
-        folder_name="report_${current_date}_${current_time}"
-        mkdir "destination-repo/$folder_name"
-        cp -R ./reports_allure/* "destination-repo/$folder_name"
-        echo "folder_name=$folder_name" >> $GITHUB_ENV
-        echo "current_datetime=$(date +'%Y-%m-%d %H:%M:%S (%Z)')" >> $GITHUB_ENV
-        if [ "${{ steps.test.outcome }}" = "success" ]; then
-        echo "color=#36a64f" >> $GITHUB_ENV
-        echo "test_status=Pass" >> $GITHUB_ENV
-        else
-        echo "color=#ff0000" >> $GITHUB_ENV
-        echo "test_status=Fail" >> $GITHUB_ENV
-        fi
-        cd destination-repo
-        git config --global user.name "trang63"
-        git config --global user.email "thantrang0603@gmail.com"
-        git add .
-        git commit -m "Upload Allure Report"
-        git push https://${{ secrets.ACCESS_KEY }}@github.com/trang63/allure_report.git
-    - name: Notify slack
-      if: success() || failure()
-      uses: slackapi/slack-github-action@v1.24.0
-      with:
-        # For posting a rich message using Block Kit
-        payload: |
-          {
-            "attachments": [
-              {
-                "color": "${{ env.color }}",
-                "blocks": [
-                  {
-                    "type": "section",
-                    "fields": [
-                      {
-                        "type": "mrkdwn",
-                        "text": "*Testsuit:*\n Regression"
-                      },
-                      {
-                        "type": "mrkdwn",
-                        "text": "*Test Result:*\n${{ env.test_status }}"
-                      },
-                      {
-                        "type": "mrkdwn",
-                        "text": "*When:*\n${{ env.current_datetime }}"
-                      },
-                      {
-                        "type": "mrkdwn",
-                        "text": "*Report Link:*\n<https://trang63.github.io/allure_report/${{ env.folder_name }}|Click here>"
-                      }
-                    ]
-                  }
-                ]
-              }
-            ]
-          }
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
-        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8 pytest
+          pip install -r requirements.txt
+      - name: Install Node.js and npm
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+      - name: Install allure-commandline
+        run: npm install -g allure-commandline
+      - name: Lint with flake8
+        run: |
+          # stop the build if there are Python syntax errors or undefined names
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+      - name: Test with pytest
+        id: test
+        run: pytest -n auto --dist loadfile  --alluredir=reports ./tests
+      - name: Generate Allure Report
+        if: success() || failure()
+        run: |
+          git clone https://github.com/trang63/allure_report.git destination-repo
+          mkdir reports/history
+          cp -R destination-repo/allure-history/* reports/history
+          allure generate reports -o reports_allure
+          sudo systemsetup -settimezone "Asia/Ho_Chi_Minh"
+          current_date=$(date +%Y-%m-%d)
+          current_time=$(date +%H-%M-%S)
+          folder_name="report_${current_date}_${current_time}"
+          mkdir "destination-repo/$folder_name"
+          cp -R ./reports_allure/* "destination-repo/$folder_name"
+          echo "folder_name=$folder_name" >> $GITHUB_ENV
+          echo "current_datetime=$(date +'%Y-%m-%d %H:%M:%S (%Z)')" >> $GITHUB_ENV
+          if [ "${{ steps.test.outcome }}" = "success" ]; then
+          echo "color=#36a64f" >> $GITHUB_ENV
+          echo "test_status=Pass" >> $GITHUB_ENV
+          else
+          echo "color=#ff0000" >> $GITHUB_ENV
+          echo "test_status=Fail" >> $GITHUB_ENV
+          fi
+      - name: Upload Allure report to Webpage
+        if: success() || failure()
+        run: |
+          cd destination-repo
+          git config --global user.name "${{ secrets.GIT_NAME }}"
+          git config --global user.email "${{ secrets.GIT_EMAIL }}"      
+          git add .
+          git commit -m "Upload Allure Report"
+          git push https://${{ secrets.ACCESS_KEY }}@github.com/${{ secrets.GIT_NAME }}/allure_report.git
+      - name: Notify slack
+        if: success() || failure()
+        uses: slackapi/slack-github-action@v1.24.0
+        with:
+          # For posting a rich message using Block Kit
+          payload: |
+            {
+              "attachments": [
+                {
+                  "color": "${{ env.color }}",
+                  "blocks": [
+                    {
+                      "type": "section",
+                      "fields": [
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Testsuit:*\n Regression"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Test Result:*\n${{ env.test_status }}"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*When:*\n${{ env.current_datetime }}"
+                        },
+                        {
+                          "type": "mrkdwn",
+                          "text": "*Report Link:*\n<https://trang63.github.io/allure_report/${{ env.folder_name }}|Click here>"
+                        }
+                      ]
+                    }
+                  ]
+                }
+              ]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
